# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            ModUni
tagline:          'Searching for semantic universals in the modal domain'
description:      'NWO project "Searching for semantic universals in the modal domain"'
url:              http://wataruuegaki.com/modal-universals/
baseurl:          /modal-universals

author:
  name:           'Wataru Uegaki'
  url:            https://wataruuegaki.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/wuegaki/
