# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            ModUni
tagline:          'A Jekyll theme'
description:      'NWO project "Searching for semantic universals in the modal domain"'
url:              http://wataruuegaki.com/modal-universals/
baseurl:          /

author:
  name:           'Wataru Uegaki'
  url:            https://twitter.com/wataruu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/wuegaki/
